(newline)
(display "loading program-generator generator")
(newline)
(load "cogen-record.scm")
(load "pp.scm")
(define p pretty-print)
(load "auxiliary.scm")
(load "cogen-env.scm")
(load "cogen-abssyn.scm") 
(load "cogen-scheme.scm")
(load "cogen-oca.scm")
(load "cogen-skeleton.scm")
(load "cogen-eq-flow.scm")
;;; to run the generating extension
(load "cogen-ctors.scm")
(load "cogen-library.scm")
(load "cogen-cps.scm")		; in cps
(load "cogen-residual.scm")
;;; to generate the generating extension
(load "cogen-driver.scm") 
