#!/bin/sh
cogen_image=$HOME/soft/pe/cps-mcogen/batch.image
heap_size=4000000
(echo ",batch on";
 echo "(cogen-main '("
 while test "x$1" != "x"; do
  echo \"$1\"
  shift
 done;
 echo "))") | scheme48 -h $heap_size -i $cogen_image
exit $?
